### ISSUE TITLE
Support PubSubHubBub for Hubzilla feeds

### ISSUE THREAD

**Issue by singpolyma** [redmatrix/hubzilla#257]
This enables real-time notification to feed consumers, which is required by many consumers of social feeds (such as GNU Social)

**Comment by redmatrix** [comment]
It is relatively easy to port the PuSH implementation from Friendica. I would refer would-be implementors to that work. 

The reason I have not made this a project default and begun work on it is because the primary PuSH consumer is GNU-social. I need to know that the long standing StatusNet attribution bug on feeds has been fixed. That means if a feed arrives with comments from different authors, are they correctly attributed to the correct authors or are they still attributed to the owner of the feed?

Our feeds contain comments by multiple authors (correctly attributed). Changing this as we once did for Friendica just to appease StatusNet's (now GNU-Social) broken software is not negotiable.

**Comment by singpolyma** [comment]
I GNU social I broken we can certainly fix it (since it is active and community maintained now). I, certainly, would have some incentive to fix this in GNU social if still present (though I do not consume PuSH using gnu social myself)

**Comment by redmatrix** [comment]
Haven't yet tested (I don't really have any tools to test PuSH end-to-end at the moment) but we've got an addon (aptly named pubsubhubbub) which should provide pubsubhubbub support. If there are any issues they should be fairly easy to fix - it isn't a complicated protocol or plugin.

**Comment by singpolyma** [comment]
@redmatrix is the plugin up somewhere?  Happy to help with testing

**Comment by jeroenpraat** [comment]
@singpolyma The plugin is our addon repo here: https://github.com/redmatrix/hubzilla-addons

    - For installing addons

        - First you should be **on** your website folder

            cd mywebsite

    - Then you should clone the addon repository (separately). We'll give this repository
         a nickname of 'matrix'. You can pull in other hubzilla addon repositories by 
         giving them different nicknames.

            util/add_addon_repo https://github.com/redmatrix/hubzilla-addons.git matrix

    - For keeping the addon tree updated, you should be on your top level website 
		directory and issue an update command for that repository.

            cd mywebsite
            util/update_addon_repo matrix

**Comment by redmatrix** [comment]
After a few false starts this appears to be working now - I am able to follow my hubzilla channel from GNU-social using pubsubhubbub.
