### ISSUE TITLE
Register policy not updated at nodeinfo

### ISSUE THREAD

**Issue by AlfredSK** [redmatrix/hubzilla#988]
I have set register policy to 'open' without invitation. In admin panel it looks okay. I checked the database too. 'system' 'register_policy' is set to 'v' => '2'.

But if I check .../nodeinfo/1.0 and .../nodeinfo/2.0 it shows 'openRegistrations: false'.

So, my hub is listed on the-federation.info as 'closed'.

**Comment by AlfredSK** [comment]
Yep. That's the one. :-) 
Okay. Thanks. I didn't know siteinfo/json. Thanks for the hint.
But still, nodeinfo shows the registration policy as closed.

**Comment by elvecio** [comment]
https://github.com/redmatrix/hubzilla/issues/732

**Comment by zotlabs** [comment]
Thanks - this bug has been present for a while, but the-federation had a couple of bugs which prevented it from seeing nodeinfo and using the old statistics.json instead. I created workarounds for the-federation.info issues several days ago so now we're actually seeing nodeinfo information there. I've fixed this latest issue upstream - it should land in hubzilla in a day or two.

**Comment by AlfredSK** [comment]
> I've fixed this latest issue upstream

There is an upstream repo? Didn't know that. I was always wondering why I don't see PRs here but still get updates when I git pull from dev. :-)

Will the fix land in 'RC' or in 'dev'?

**Comment by git-marijus** [comment]
It is already merged in dev and rc.

**Comment by AlfredSK** [comment]
Fixed! ...and closed.
Thanks!
